export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    // Apps y paquetes del monorepo + modulos de la spec.
    'scope-enum': [
      2,
      'always',
      [
        'api',
        'pwa',
        'landing',
        'domain',
        'schemas',
        'types',
        'ui',
        'client',
        'config',
        'auth',
        'account',
        'equipment',
        'sights',
        'marks',
        'sharing',
        'billing',
        'subs',
        'entitlements',
        'notifications',
        'crm',
        'i18n',
        'infra',
        'ci',
        'docs',
        'deps',
        'repo',
      ],
    ],
    'subject-case': [0],
    'header-max-length': [2, 'always', 100],
  },
};
